In [1]:
from src.ingestion.load_data import DataLoader
from src.ingestion.validate_data import DataValidator

In [2]:
loader = DataLoader()

df = loader.load_data(1000)

validator = DataValidator()

validator.validate(df)

Duplicate IDs : 0
id            0
title         0
abstract      0
authors       0
categories    0
dtype: int64

In [3]:
df.head()

,id,submitter,authors,title,comments,journal-ref,doi,report-no,categories,license,abstract,versions,update_date,authors_parsed
0,704.0001,Pavel Nadolsky,"C. Bal\'azs, E. L. Berger, P. M. Nadolsky, C.-...",Calculation of prompt diphoton production cros...,"37 pages, 15 figures; published version","Phys.Rev.D76:013009,2007",10.1103/PhysRevD.76.013009,ANL-HEP-PR-07-12,hep-ph,NaN,A fully differential calculation in perturba...,"[{'version': 'v1', 'created': 'Mon, 2 Apr 2007...",2008-11-26,"[[Balázs, C., ], [Berger, E. L., ], [Nadolsky,..."
1,704.0002,Louis Theran,Ileana Streinu and Louis Theran,Sparsity-certifying Graph Decompositions,To appear in Graphs and Combinatorics,NaN,NaN,NaN,math.CO cs.CG,http://arxiv.org/licenses/nonexclusive-distrib...,"We describe a new algorithm, the $(k,\ell)$-...","[{'version': 'v1', 'created': 'Sat, 31 Mar 200...",2008-12-13,"[[Streinu, Ileana, ], [Theran, Louis, ]]"
2,704.0003,Hongjun Pan,Hongjun Pan,The evolution of the Earth-Moon system based o...,"23 pages, 3 figures",NaN,NaN,NaN,physics.gen-ph,NaN,The evolution of Earth-Moon system is descri...,"[{'version': 'v1', 'created': 'Sun, 1 Apr 2007...",2008-01-13,"[[Pan, Hongjun, ]]"
3,704.0004,David Callan,David Callan,A determinant of Stirling cycle numbers counts...,11 pages,NaN,NaN,NaN,math.CO,NaN,We show that a determinant of Stirling cycle...,"[{'version': 'v1', 'created': 'Sat, 31 Mar 200...",2007-05-23,"[[Callan, David, ]]"
4,704.0005,Alberto Torchinsky,Wael Abu-Shammala and Alberto Torchinsky,From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\a...,NaN,"Illinois J. Math. 52 (2008) no.2, 681-689",NaN,NaN,math.CA math.FA,NaN,In this paper we show how to compute the $\L...,"[{'version': 'v1', 'created': 'Mon, 2 Apr 2007...",2013-10-15,"[[Abu-Shammala, Wael, ], [Torchinsky, Alberto, ]]"

In [4]:
df.shape

(1000, 14)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              1000 non-null   float64
 1   submitter       1000 non-null   str
 2   authors         1000 non-null   str
 3   title           1000 non-null   str
 4   comments        901 non-null    str
 5   journal-ref     573 non-null    str
 6   doi             663 non-null    str
 7   report-no       78 non-null     str
 8   categories      1000 non-null   str
 9   license         61 non-null     str
 10  abstract        1000 non-null   str
 11  versions        1000 non-null   object
 12  update_date     1000 non-null   str
 13  authors_parsed  1000 non-null   object
dtypes: float64(1), object(2), str(11)
memory usage: 1.1+ MB

In [6]:
df.describe(include="all")

,id,submitter,authors,title,comments,journal-ref,doi,report-no,categories,license,abstract,versions,update_date,authors_parsed
count,1000.000000,1000,1000,1000,901,573,663,78,1000,61,1000,1000,1000,1000
unique,NaN,921,965,1000,816,573,663,78,309,2,998,1000,255,963
top,NaN,Igor Grabec,I. Grabec,Calculation of prompt diphoton production cros...,"4 pages, 4 figures","Phys.Rev.D76:013009,2007",10.1103/PhysRevD.76.013009,ANL-HEP-PR-07-12,astro-ph,http://arxiv.org/licenses/nonexclusive-distrib...,Zero-divisors (ZDs) derived by Cayley-Dickso...,"[{'version': 'v1', 'created': 'Mon, 2 Apr 2007...",2007-05-23,"[[Grabec, I., ]]"
freq,NaN,7,4,1,9,1,1,1,179,59,2,1,200,4
mean,704.050050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.028882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,704.000100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,704.025075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,704.050050,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,704.075025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,704.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.isnull().sum()

id                  0
submitter           0
authors             0
title               0
comments           99
journal-ref       427
doi               337
report-no         922
categories          0
license           939
abstract            0
versions            0
update_date         0
authors_parsed      0
dtype: int64

In [8]:
df["categories"].value_counts().head(20)

categories
astro-ph                             179
quant-ph                              42
hep-th                                40
hep-ph                                37
cond-mat.mes-hall                     29
cond-mat.str-el                       27
cond-mat.mtrl-sci                     25
gr-qc                                 24
nucl-th                               16
nucl-ex                               13
math.CO                               12
physics.gen-ph                        11
hep-ex                                11
math.PR                               10
physics.optics                        10
cs.IT math.IT                         10
cond-mat.other                        10
cond-mat.supr-con                      9
math.NT                                8
cond-mat.supr-con cond-mat.str-el      8
Name: count, dtype: int64

In [9]:
df["abstract_length"] = df["abstract"].str.len()

df["abstract_length"].describe()

count    1000.000000
mean      799.138000
std       401.299786
min        44.000000
25%       507.750000
50%       731.500000
75%      1035.250000
max      1869.000000
Name: abstract_length, dtype: float64