In [1]:
import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
df = pd.read_parquet("../data/processed/arxiv_ml.parquet")

df.head()

,id,title,authors,category,text_raw,text_ml
0,704.0001,Calculation of prompt diphoton production cros...,"C. Bal\'azs, E. L. Berger, P. M. Nadolsky, C.-...",hep-ph,Calculation of prompt diphoton production cros...,calculation prompt diphoton production cross s...
1,704.0002,Sparsity-certifying Graph Decompositions,Ileana Streinu and Louis Theran,math.CO,Sparsity-certifying Graph Decompositions We ...,sparsity certify graph decomposition describe ...
2,704.0003,The evolution of the Earth-Moon system based o...,Hongjun Pan,physics.gen-ph,The evolution of the Earth-Moon system based o...,evolution earth moon system base dark matter f...
3,704.0004,A determinant of Stirling cycle numbers counts...,David Callan,math.CO,A determinant of Stirling cycle numbers counts...,determinant stirling cycle number count unlabe...
4,704.0005,From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\a...,Wael Abu-Shammala and Alberto Torchinsky,math.CA,From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\a...,dyadic lambda alpha lambda alpha compute lambd...

In [2]:
model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

c:\Users\DELL\Desktop\Cdac\aiml-project\myenv\Lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\DELL\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [5]:
embeddings = model.encode(
    df["text_raw"].tolist(),
    batch_size=32,
    show_progress_bar=True,
    convert_to_numpy=True
)

Batches:   0%|          | 0/32 [00:00<?, ?it/s]

In [6]:
print(embeddings.shape)

(1000, 384)

In [7]:
embeddings[0]

array([-1.58419624e-01, -1.01032890e-02,  2.19406607e-03,  4.50048447e-02,
        3.63339409e-02, -4.24838215e-02, -4.61273342e-02,  5.97007573e-02,
        4.23808470e-02, -3.25520933e-02,  1.74576491e-02, -3.14672515e-02,
       -3.97230797e-02, -3.76211759e-03,  1.54057713e-02,  2.37496514e-02,
       -2.08473932e-02, -5.65718412e-02, -8.76072198e-02, -1.72332283e-02,
       -5.22109009e-02,  2.45143455e-02, -3.29107568e-02,  2.20729280e-02,
        7.40172789e-02, -9.27654058e-02, -3.29313502e-02, -9.33981035e-03,
        4.80712540e-02,  1.16254399e-02,  2.55359132e-02, -1.39606092e-02,
       -2.30887458e-02,  3.90545130e-02,  7.85364956e-02,  4.41619456e-02,
        3.04403864e-02, -9.58790928e-02,  3.70898806e-02, -2.86279954e-02,
        4.57841083e-02,  8.33052211e-03,  2.55478336e-03, -1.64655522e-02,
        6.29489794e-02,  2.37136800e-02,  2.86393948e-02, -5.63222356e-02,
       -5.08890785e-02,  7.98176229e-03,  7.28131458e-02,  5.07254414e-02,
       -1.26286773e-02,  6.26631230e-02, -4.72402312e-02,  2.38347650e-02,
       -9.01646854e-04, -9.45941955e-02,  3.15728486e-02,  6.81862086e-02,
       -1.24166481e-01,  2.74499180e-03, -7.08312839e-02, -1.84243768e-02,
        2.94866376e-02, -1.29097067e-02, -2.11108122e-02,  1.82387121e-02,
        3.58969681e-02,  4.07623462e-02,  9.71366372e-03,  2.84299217e-02,
       -6.99018985e-02, -3.25464942e-02, -6.74047042e-03,  3.56469750e-02,
        5.23138158e-02,  6.51656045e-03, -2.22635213e-02, -8.51297602e-02,
        5.45110591e-02, -6.46327483e-03,  1.02819903e-02, -5.19056022e-02,
        3.96366464e-03,  1.84560753e-02, -4.38921377e-02,  1.13436453e-01,
        7.39414524e-03, -2.93080527e-02, -2.32888442e-02, -1.15742594e-01,
       -4.52213287e-02, -1.06922351e-02,  7.27430405e-03,  1.52374119e-01,
        7.17307925e-02, -8.25883299e-02,  5.81779480e-02,  3.64770070e-02,
        3.16789560e-02, -1.24491183e-02,  2.17908211e-02,  1.16580287e-02,
        4.61653695e-02, -8.28660931e-03,  3.70806418e-02,  7.99003690e-02,
       -8.72610137e-03, -7.52423704e-02,  1.08589664e-01,  2.99007650e-02,
        1.94859635e-02, -5.87924086e-02, -6.74462616e-02,  5.24335578e-02,
       -1.24561377e-02,  3.51312682e-02, -2.05949862e-02, -6.88472539e-02,
        3.52056175e-02,  5.95391076e-03,  3.46042141e-02,  5.70850931e-02,
        1.83570068e-02, -2.61438116e-02, -2.17091143e-02,  6.53003348e-33,
        7.47711957e-02, -1.68249067e-02,  2.99938973e-02, -2.85599139e-02,
       -6.90890700e-02,  4.87971492e-02,  6.40955847e-03, -5.80755956e-02,
       -1.22097731e-02,  1.82333253e-02, -6.56104311e-02, -6.74500540e-02,
       -1.46980933e-03, -8.79164115e-02, -3.11713032e-02, -6.35388866e-03,
       -2.70706881e-02,  5.10014072e-02, -1.64383221e-02,  5.19554578e-02,
        6.56221947e-03,  5.05856238e-03, -6.03593066e-02, -2.55696767e-04,
        4.80325557e-02,  1.00614622e-01, -1.57156363e-02,  4.24213298e-02,
       -1.17161028e-01,  2.59384159e-02, -9.76166315e-03,  1.01421103e-01,
       -9.14173387e-03,  6.89753741e-02,  2.83881258e-02, -4.20790352e-02,
       -5.06843515e-02, -5.18812351e-02,  4.40989621e-02, -8.57698638e-03,
        2.32553836e-02,  5.09278551e-02, -7.71387741e-02, -7.43656158e-02,
        2.11829115e-02, -2.20440216e-02,  7.03333169e-02, -1.88905448e-02,
       -1.50830271e-02, -3.08008790e-02, -1.43847940e-03,  3.91814038e-02,
        2.17885859e-02, -5.95143158e-03,  1.66613422e-02, -3.36181819e-02,
        1.10017449e-01, -2.55975444e-02,  6.57297373e-02,  9.84055176e-02,
       -2.50298586e-02,  4.30489667e-02, -1.00908717e-02,  1.56858992e-02,
       -8.68644044e-02,  1.85500607e-02, -3.14553902e-02,  1.31001631e-02,
       -1.54492690e-03,  6.08222894e-02, -5.98657131e-03,  3.26860137e-02,
       -2.00406127e-02, -1.15822986e-01,  1.56173632e-01, -8.29395559e-03,
       -9.11280885e-03,  6.62591383e-02,  8.76442622e-03,  3.34149189e-02,
        1.23260468e-02, -1.31546063e-02, -4.03943993e-02,  2.50102375e-02,
       -2.55912486e-02,  4.42947028e-03, -4.00438458e-02, -1.76787227e-02,
       -7.23300576e-02,  2.50427565e-03, -5.10425270e-02,  1.67610310e-02,
        8.89281034e-02, -1.93315037e-02, -7.77041167e-02, -6.27462060e-33,
       -5.93651980e-02,  3.74425389e-02,  1.32419234e-02,  2.38894429e-02,
       -6.73942193e-02, -5.87021820e-02, -3.66271213e-02, -3.75952832e-02,
        3.34158242e-02,  5.97185902e-02, -1.70665357e-04,  2.25162413e-02,
       -1.26090422e-01, -4.50046882e-02, -3.15430798e-02,  6.95346072e-02,
        1.88738480e-02,  1.78431794e-02,  4.49304171e-02,  2.07516160e-02,
        4.24226262e-02,  2.92167459e-02,  2.85902359e-02,  2.63762951e-04,
        7.01658195e-03, -2.10189857e-02,  9.19093043e-02, -9.69796181e-02,
        4.25845720e-02, -4.92515191e-02, -8.13385546e-02, -4.80816290e-02,
        1.43528488e-02,  9.43768919e-02,  3.02425250e-02, -3.58745083e-02,
        8.95039886e-02,  1.46695850e-02,  2.72146370e-02, -3.08875795e-02,
        9.21853930e-02,  7.66616836e-02, -2.76540127e-02,  1.08490186e-02,
        1.09764813e-02,  4.68133725e-02, -5.12229092e-02,  2.91606747e-02,
       -2.13879589e-02, -1.89460963e-02, -4.39427793e-02,  1.57419331e-02,
        2.90969163e-02,  8.24277475e-02, -5.88755831e-02, -3.82029153e-02,
        5.49080432e-04,  1.01537667e-02, -2.34922618e-02, -1.22049162e-02,
       -8.41157958e-02, -1.22235194e-01, -4.72524529e-03, -2.92946417e-02,
        3.10250074e-02,  4.44719829e-02, -5.29744402e-02,  6.46451637e-02,
        2.21199379e-03, -3.73312123e-02,  2.03519091e-02, -8.20630044e-02,
        6.67845383e-02, -3.02862022e-02, -2.60424186e-02,  7.54882488e-03,
        1.03953794e-01, -1.04797959e-01,  1.26535207e-01,  6.02299767e-03,
       -4.59213145e-02,  4.16785665e-02, -1.96402762e-02, -6.30243961e-03,
        2.74808966e-02,  6.59475848e-02, -2.47818790e-02,  7.15549067e-02,
       -1.20014958e-02, -8.79021361e-02, -8.81931782e-02,  4.08429913e-02,
        1.09886624e-01,  3.66124101e-02,  7.78471529e-02, -4.71431818e-08,
        3.52571681e-02, -6.10867627e-02, -3.32384147e-02, -9.35222051e-05,
        5.07062040e-02,  6.76490227e-03, -4.01043221e-02,  2.28290614e-02,
       -2.76570357e-02,  5.19868210e-02,  8.15637261e-02, -8.84366035e-03,
       -4.32267152e-02, -9.97433066e-02, -1.51897455e-02,  4.38365601e-02,
        5.46892826e-03, -5.38300388e-02, -2.98271943e-02,  7.77675351e-03,
        5.95993921e-02,  4.29890193e-02,  6.66145310e-02, -1.17053157e-02,
       -1.03919841e-01,  6.91838656e-03,  2.13645006e-04,  2.41002683e-02,
       -1.29690478e-02, -4.55573313e-02,  3.54435556e-02, -4.83084731e-02,
       -6.12901561e-02,  3.75673585e-02,  6.44825818e-03, -2.92311087e-02,
       -6.04207106e-02, -9.07492917e-03,  1.53272092e-01,  8.28786045e-02,
       -4.52468358e-02,  4.39561233e-02, -4.33628634e-02,  8.10984373e-02,
       -4.10575159e-02,  1.15416367e-02, -3.98995578e-02, -6.86753020e-02,
       -5.00607118e-02,  3.61619107e-02, -3.02182399e-02, -3.07145435e-02,
        1.68054819e-03, -5.83564900e-02, -6.01688512e-02, -8.18250049e-03,
       -2.31759194e-02, -3.72114591e-02,  5.25829056e-03, -1.17996875e-02,
        1.13112651e-01, -1.67471990e-02, -4.74616997e-02,  5.13064712e-02],
      dtype=float32)

In [8]:
print(embeddings[0][:10])

[-0.15841962 -0.01010329  0.00219407  0.04500484  0.03633394 -0.04248382
 -0.04612733  0.05970076  0.04238085 -0.03255209]

In [9]:
print(type(embeddings))
print(embeddings.dtype)

<class 'numpy.ndarray'>
float32

In [10]:
semantic_similarity = cosine_similarity(
    embeddings
)

print(semantic_similarity.shape)

(1000, 1000)

In [11]:
indices = pd.Series(
    df.index,
    index=df["title"]
).drop_duplicates()

In [12]:
def semantic_recommend(title, top_n=5):

    idx = indices[title]

    sim_scores = list(
        enumerate(
            semantic_similarity[idx]
        )
    )

    sim_scores = sorted(
        sim_scores,
        key=lambda x: x[1],
        reverse=True
    )

    sim_scores = sim_scores[1:top_n+1]

    paper_indices = [i[0] for i in sim_scores]

    recommendations = df.iloc[
        paper_indices
    ][
        [
            "title",
            "authors",
            "category"
        ]
    ].copy()

    recommendations["Similarity"] = [
        round(score[1] * 100,2)
        for score in sim_scores
    ]

    return recommendations

In [13]:
semantic_recommend(
    df.iloc[0]["title"]
)

,title,authors,category,Similarity
839,Associated production of the charged Higgs bos...,"Yao-Bei Liu, Jie-Fen Shen",hep-ph,64.519997
759,"Search for Heavy, Long-Lived Particles that De...",A. Abulencia et al. (CDF Collaboration),hep-ex,63.930000
641,Direct photons and dileptons via color dipoles,"B. Z. Kopeliovich, A. H. Rezaeian, H. J. Pirne...",hep-ph,60.990002
234,The Determination of the Helicity of $W'$ Boso...,Thomas G. Rizzo,hep-ph,59.459999
637,Polarizations of J/psi and psi(2S) Mesons Prod...,CDF Collaboration,hep-ex,59.310001

In [14]:
semantic_recommend(df.iloc[0]["title"])

,title,authors,category,Similarity
839,Associated production of the charged Higgs bos...,"Yao-Bei Liu, Jie-Fen Shen",hep-ph,64.519997
759,"Search for Heavy, Long-Lived Particles that De...",A. Abulencia et al. (CDF Collaboration),hep-ex,63.930000
641,Direct photons and dileptons via color dipoles,"B. Z. Kopeliovich, A. H. Rezaeian, H. J. Pirne...",hep-ph,60.990002
234,The Determination of the Helicity of $W'$ Boso...,Thomas G. Rizzo,hep-ph,59.459999
637,Polarizations of J/psi and psi(2S) Mesons Prod...,CDF Collaboration,hep-ex,59.310001